# Configuration for rustfmt (stable features only)
# https://rust-lang.github.io/rustfmt/

edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4

# Imports
reorder_imports = true

# Functions and control flow
force_explicit_abi = true

# Misc
remove_nested_parens = true
use_field_init_shorthand = false
use_try_shorthand = false

# The following features require nightly rustfmt:
# imports_granularity = "Crate"
# group_imports = "StdExternalCrate"
# wrap_comments = true
# comment_width = 80
# normalize_comments = true
# format_strings = false
# format_macro_matchers = true
# format_macro_bodies = true
# struct_lit_single_line = true
# fn_single_line = false
# where_single_line = false
# enum_discrim_align_threshold = 0
# force_multiline_blocks = false
